leftnav:
- identifier: f6cb2092-2b6e-4ff9-4a16-83329d9fe978
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 40c34009-951e-21d9-f061-4937e20581ff
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 25866a1a-6bc9-6f94-4e83-050a5a373c36
  name: Readings
  pageRef: /pages/readings/
  weight: 30
- identifier: 23048ea7-dc7f-2b27-c870-329c2a067e77
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: f8b144cf-54af-9cab-9714-5e3892ebc18e
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 50
